/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RdoIdRouteImport } from './routes/rdo.$id'
import { Route as ObraIdRouteImport } from './routes/obra.$id'
import { Route as RdoIdEditarRouteImport } from './routes/rdo.$id.editar'
import { Route as ObraIdRdoNovoRouteImport } from './routes/obra.$id.rdo.novo'

const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RdoIdRoute = RdoIdRouteImport.update({
  id: '/rdo/$id',
  path: '/rdo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraIdRoute = ObraIdRouteImport.update({
  id: '/obra/$id',
  path: '/obra/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RdoIdEditarRoute = RdoIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => RdoIdRoute,
} as any)
const ObraIdRdoNovoRoute = ObraIdRdoNovoRouteImport.update({
  id: '/rdo/novo',
  path: '/rdo/novo',
  getParentRoute: () => ObraIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/obra/$id': typeof ObraIdRouteWithChildren
  '/rdo/$id': typeof RdoIdRouteWithChildren
  '/rdo/$id/editar': typeof RdoIdEditarRoute
  '/obra/$id/rdo/novo': typeof ObraIdRdoNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/obra/$id': typeof ObraIdRouteWithChildren
  '/rdo/$id': typeof RdoIdRouteWithChildren
  '/rdo/$id/editar': typeof RdoIdEditarRoute
  '/obra/$id/rdo/novo': typeof ObraIdRdoNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/obra/$id': typeof ObraIdRouteWithChildren
  '/rdo/$id': typeof RdoIdRouteWithChildren
  '/rdo/$id/editar': typeof RdoIdEditarRoute
  '/obra/$id/rdo/novo': typeof ObraIdRdoNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/obra/$id'
    | '/rdo/$id'
    | '/rdo/$id/editar'
    | '/obra/$id/rdo/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/obra/$id'
    | '/rdo/$id'
    | '/rdo/$id/editar'
    | '/obra/$id/rdo/novo'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/obra/$id'
    | '/rdo/$id'
    | '/rdo/$id/editar'
    | '/obra/$id/rdo/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ObraIdRoute: typeof ObraIdRouteWithChildren
  RdoIdRoute: typeof RdoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdo/$id': {
      id: '/rdo/$id'
      path: '/rdo/$id'
      fullPath: '/rdo/$id'
      preLoaderRoute: typeof RdoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra/$id': {
      id: '/obra/$id'
      path: '/obra/$id'
      fullPath: '/obra/$id'
      preLoaderRoute: typeof ObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdo/$id/editar': {
      id: '/rdo/$id/editar'
      path: '/editar'
      fullPath: '/rdo/$id/editar'
      preLoaderRoute: typeof RdoIdEditarRouteImport
      parentRoute: typeof RdoIdRoute
    }
    '/obra/$id/rdo/novo': {
      id: '/obra/$id/rdo/novo'
      path: '/rdo/novo'
      fullPath: '/obra/$id/rdo/novo'
      preLoaderRoute: typeof ObraIdRdoNovoRouteImport
      parentRoute: typeof ObraIdRoute
    }
  }
}

interface ObraIdRouteChildren {
  ObraIdRdoNovoRoute: typeof ObraIdRdoNovoRoute
}

const ObraIdRouteChildren: ObraIdRouteChildren = {
  ObraIdRdoNovoRoute: ObraIdRdoNovoRoute,
}

const ObraIdRouteWithChildren =
  ObraIdRoute._addFileChildren(ObraIdRouteChildren)

interface RdoIdRouteChildren {
  RdoIdEditarRoute: typeof RdoIdEditarRoute
}

const RdoIdRouteChildren: RdoIdRouteChildren = {
  RdoIdEditarRoute: RdoIdEditarRoute,
}

const RdoIdRouteWithChildren = RdoIdRoute._addFileChildren(RdoIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ObraIdRoute: ObraIdRouteWithChildren,
  RdoIdRoute: RdoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
