/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecebimentoIdRouteImport } from './routes/recebimento.$id'
import { Route as RdoIdRouteImport } from './routes/rdo.$id'
import { Route as ObraIdRouteImport } from './routes/obra.$id'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as RdoIdEditarRouteImport } from './routes/rdo_.$id.editar'
import { Route as PrintRecebimentoIdRouteImport } from './routes/print.recebimento.$id'
import { Route as PrintRdoRdoIdRouteImport } from './routes/print.rdo.$rdoId'
import { Route as PrintDiarioObraIdRouteImport } from './routes/print.diario.$obraId'
import { Route as PObraIdRouteImport } from './routes/p.obra.$id'
import { Route as ObraIdRecebimentoNovoRouteImport } from './routes/obra_.$id.recebimento.novo'
import { Route as ObraIdRdoNovoRouteImport } from './routes/obra_.$id.rdo.novo'

const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoIdRoute = RecebimentoIdRouteImport.update({
  id: '/recebimento/$id',
  path: '/recebimento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RdoIdRoute = RdoIdRouteImport.update({
  id: '/rdo/$id',
  path: '/rdo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraIdRoute = ObraIdRouteImport.update({
  id: '/obra/$id',
  path: '/obra/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RdoIdEditarRoute = RdoIdEditarRouteImport.update({
  id: '/rdo_/$id/editar',
  path: '/rdo/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRecebimentoIdRoute = PrintRecebimentoIdRouteImport.update({
  id: '/print/recebimento/$id',
  path: '/print/recebimento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRdoRdoIdRoute = PrintRdoRdoIdRouteImport.update({
  id: '/print/rdo/$rdoId',
  path: '/print/rdo/$rdoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintDiarioObraIdRoute = PrintDiarioObraIdRouteImport.update({
  id: '/print/diario/$obraId',
  path: '/print/diario/$obraId',
  getParentRoute: () => rootRouteImport,
} as any)
const PObraIdRoute = PObraIdRouteImport.update({
  id: '/p/obra/$id',
  path: '/p/obra/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraIdRecebimentoNovoRoute = ObraIdRecebimentoNovoRouteImport.update({
  id: '/obra_/$id/recebimento/novo',
  path: '/obra/$id/recebimento/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraIdRdoNovoRoute = ObraIdRdoNovoRouteImport.update({
  id: '/obra_/$id/rdo/novo',
  path: '/obra/$id/rdo/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/obra/$id': typeof ObraIdRoute
  '/rdo/$id': typeof RdoIdRoute
  '/recebimento/$id': typeof RecebimentoIdRoute
  '/p/obra/$id': typeof PObraIdRoute
  '/print/diario/$obraId': typeof PrintDiarioObraIdRoute
  '/print/rdo/$rdoId': typeof PrintRdoRdoIdRoute
  '/print/recebimento/$id': typeof PrintRecebimentoIdRoute
  '/rdo/$id/editar': typeof RdoIdEditarRoute
  '/obra/$id/rdo/novo': typeof ObraIdRdoNovoRoute
  '/obra/$id/recebimento/novo': typeof ObraIdRecebimentoNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/obra/$id': typeof ObraIdRoute
  '/rdo/$id': typeof RdoIdRoute
  '/recebimento/$id': typeof RecebimentoIdRoute
  '/p/obra/$id': typeof PObraIdRoute
  '/print/diario/$obraId': typeof PrintDiarioObraIdRoute
  '/print/rdo/$rdoId': typeof PrintRdoRdoIdRoute
  '/print/recebimento/$id': typeof PrintRecebimentoIdRoute
  '/rdo/$id/editar': typeof RdoIdEditarRoute
  '/obra/$id/rdo/novo': typeof ObraIdRdoNovoRoute
  '/obra/$id/recebimento/novo': typeof ObraIdRecebimentoNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/obra/$id': typeof ObraIdRoute
  '/rdo/$id': typeof RdoIdRoute
  '/recebimento/$id': typeof RecebimentoIdRoute
  '/p/obra/$id': typeof PObraIdRoute
  '/print/diario/$obraId': typeof PrintDiarioObraIdRoute
  '/print/rdo/$rdoId': typeof PrintRdoRdoIdRoute
  '/print/recebimento/$id': typeof PrintRecebimentoIdRoute
  '/rdo_/$id/editar': typeof RdoIdEditarRoute
  '/obra_/$id/rdo/novo': typeof ObraIdRdoNovoRoute
  '/obra_/$id/recebimento/novo': typeof ObraIdRecebimentoNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/login'
    | '/obras'
    | '/admin/usuarios'
    | '/obra/$id'
    | '/rdo/$id'
    | '/recebimento/$id'
    | '/p/obra/$id'
    | '/print/diario/$obraId'
    | '/print/rdo/$rdoId'
    | '/print/recebimento/$id'
    | '/rdo/$id/editar'
    | '/obra/$id/rdo/novo'
    | '/obra/$id/recebimento/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/login'
    | '/obras'
    | '/admin/usuarios'
    | '/obra/$id'
    | '/rdo/$id'
    | '/recebimento/$id'
    | '/p/obra/$id'
    | '/print/diario/$obraId'
    | '/print/rdo/$rdoId'
    | '/print/recebimento/$id'
    | '/rdo/$id/editar'
    | '/obra/$id/rdo/novo'
    | '/obra/$id/recebimento/novo'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/login'
    | '/obras'
    | '/admin/usuarios'
    | '/obra/$id'
    | '/rdo/$id'
    | '/recebimento/$id'
    | '/p/obra/$id'
    | '/print/diario/$obraId'
    | '/print/rdo/$rdoId'
    | '/print/recebimento/$id'
    | '/rdo_/$id/editar'
    | '/obra_/$id/rdo/novo'
    | '/obra_/$id/recebimento/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  LoginRoute: typeof LoginRoute
  ObrasRoute: typeof ObrasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  ObraIdRoute: typeof ObraIdRoute
  RdoIdRoute: typeof RdoIdRoute
  RecebimentoIdRoute: typeof RecebimentoIdRoute
  PObraIdRoute: typeof PObraIdRoute
  PrintDiarioObraIdRoute: typeof PrintDiarioObraIdRoute
  PrintRdoRdoIdRoute: typeof PrintRdoRdoIdRoute
  PrintRecebimentoIdRoute: typeof PrintRecebimentoIdRoute
  RdoIdEditarRoute: typeof RdoIdEditarRoute
  ObraIdRdoNovoRoute: typeof ObraIdRdoNovoRoute
  ObraIdRecebimentoNovoRoute: typeof ObraIdRecebimentoNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/$id': {
      id: '/recebimento/$id'
      path: '/recebimento/$id'
      fullPath: '/recebimento/$id'
      preLoaderRoute: typeof RecebimentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdo/$id': {
      id: '/rdo/$id'
      path: '/rdo/$id'
      fullPath: '/rdo/$id'
      preLoaderRoute: typeof RdoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra/$id': {
      id: '/obra/$id'
      path: '/obra/$id'
      fullPath: '/obra/$id'
      preLoaderRoute: typeof ObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdo_/$id/editar': {
      id: '/rdo_/$id/editar'
      path: '/rdo/$id/editar'
      fullPath: '/rdo/$id/editar'
      preLoaderRoute: typeof RdoIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/recebimento/$id': {
      id: '/print/recebimento/$id'
      path: '/print/recebimento/$id'
      fullPath: '/print/recebimento/$id'
      preLoaderRoute: typeof PrintRecebimentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/rdo/$rdoId': {
      id: '/print/rdo/$rdoId'
      path: '/print/rdo/$rdoId'
      fullPath: '/print/rdo/$rdoId'
      preLoaderRoute: typeof PrintRdoRdoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/diario/$obraId': {
      id: '/print/diario/$obraId'
      path: '/print/diario/$obraId'
      fullPath: '/print/diario/$obraId'
      preLoaderRoute: typeof PrintDiarioObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/obra/$id': {
      id: '/p/obra/$id'
      path: '/p/obra/$id'
      fullPath: '/p/obra/$id'
      preLoaderRoute: typeof PObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra_/$id/recebimento/novo': {
      id: '/obra_/$id/recebimento/novo'
      path: '/obra/$id/recebimento/novo'
      fullPath: '/obra/$id/recebimento/novo'
      preLoaderRoute: typeof ObraIdRecebimentoNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra_/$id/rdo/novo': {
      id: '/obra_/$id/rdo/novo'
      path: '/obra/$id/rdo/novo'
      fullPath: '/obra/$id/rdo/novo'
      preLoaderRoute: typeof ObraIdRdoNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  LoginRoute: LoginRoute,
  ObrasRoute: ObrasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  ObraIdRoute: ObraIdRoute,
  RdoIdRoute: RdoIdRoute,
  RecebimentoIdRoute: RecebimentoIdRoute,
  PObraIdRoute: PObraIdRoute,
  PrintDiarioObraIdRoute: PrintDiarioObraIdRoute,
  PrintRdoRdoIdRoute: PrintRdoRdoIdRoute,
  PrintRecebimentoIdRoute: PrintRecebimentoIdRoute,
  RdoIdEditarRoute: RdoIdEditarRoute,
  ObraIdRdoNovoRoute: ObraIdRdoNovoRoute,
  ObraIdRecebimentoNovoRoute: ObraIdRecebimentoNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
